In [1]:
import pandas_datareader.data as reader

In [2]:
import pandas as pd
import datetime as dt
from dateutil.relativedelta import relativedelta

In [3]:
import json
requestBody={
  "userId": "DR33829",
  "password": "54321cms@R",
  "yob": "1988"
}

In [4]:
import requests
headers = {
  'Content-Type': 'application/json',
  'Accept': 'application/json'
}

r = requests.post('https://api.stocknote.com/login'
, data=json.dumps(requestBody)
, headers = headers)

print (r.json())

{'serverTime': '30/03/21 10:41:39', 'msgId': 'c68f69fa-b4d6-408b-9ff5-a07fd00167d1', 'status': 'Success', 'statusMessage': 'Login session token generated successfully ', 'sessionToken': 'a3f2c8842dfbf9375060d013fbd2271f', 'accountID': 'DR33829', 'accountName': 'RAJNEESH SHARMA', 'exchangeList': ['BSE', 'BFO', 'CDS', 'MCX', 'NSE'], 'orderTypeList': ['MKT', 'L', 'SL'], 'productList': ['MIS', 'CNC', 'NRML']}

In [5]:
headers = {
  'Accept': 'application/json',
  'x-session-token': 'a3f2c8842dfbf9375060d013fbd2271f'
}

r = requests.get('https://api.stocknote.com/quote/getQuote', params={
  'symbolName': 'INFRATEL'
}, headers = headers)

print (r.json())

{'serverTime': '30/03/21 10:41:55', 'msgId': 'f08997bd-4bc8-454d-be4b-46283b119364', 'status': 'Failure', 'statusMessage': 'No Symbol found for the provided symbol name and exchange.'}

In [6]:
list1= ['INFY', 'Reliance']
for name in list1:
    print(name)
    #name=[]
    headers = {
      'Accept': 'application/json',
      'x-session-token': 'a3f2c8842dfbf9375060d013fbd2271f'
    }
    name_new = name+ '_year'
    name_new = requests.get('https://api.stocknote.com/history/candleData', params={
      f'symbolName': {name},  'fromDate': '2019-10-11'
    }, headers = headers)
    #name_new = name+ '_data'
    r=name_new.json()
#l_infy= r.json()

INFY
Reliance

In [7]:
nifty_50 = ['ADANIPORTS','ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BHARTIARTL',

'BPCL',
'CIPLA',
'COALINDIA',
'DRREDDY',
'EICHERMOT',
'GAIL',
'GRASIM',
'HCLTECH',
'HDFC',
'HDFCBANK',
'HEROMOTOCO',
'HINDALCO',
'HINDUNILVR',
'BRITANNIA',
'ICICIBANK',
'INDUSINDBK',
'INFY',
'IOC',
'ITC',
'JSWSTEEL',
'KOTAKBANK',
'LT',
'M&M',
'MARUTI',
'NESTLEIND',
'NTPC',
'ONGC',
'POWERGRID',
'RELIANCE',
'SBIN',
'SUNPHARMA',
'TCS',
'TATAMOTORS',
'TATASTEEL',
'TECHM',
'TITAN',
'ULTRACEMCO',
'UPL',
'VEDL',
'WIPRO',
'SHREECEM',
'ZEEL']

In [15]:
# These are all the keys you want
key_names= nifty_50 
#key_names=['AXISBANK','BAJAJ-AUTO','BAJFINANCE']
'''['ADANIPORTS','ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BHARTIARTL',
'INFRATEL',
'BPCL',
'CIPLA',
'COALINDIA',
'DRREDDY',
'EICHERMOT',
'GAIL',
'GRASIM',
'HCLTECH',
'HDFC',
'HDFCBANK',
'HEROMOTOCO',
'HINDALCO',
'HINDUNILVR',
'BRITANNIA',
'ICICIBANK',
'INDUSINDBK',
'INFY',
'IOC',
'ITC',
'JSWSTEEL',
'KOTAKBANK',
'LT',
'M&M',
'MARUTI',
'NESTLEIND',
'NTPC',
'ONGC',
'POWERGRID',
'RELIANCE',
'SBIN',
'SUNPHARMA',
'TCS',
'TATAMOTORS',
'TATASTEEL',
'TECHM',
'TITAN',
'ULTRACEMCO',
'UPL',
'VEDL',
'WIPRO',
'SHREECEM',
'ZEEL']'''

# Holds the data you want to pass to the dataframe.
df_info = pd.DataFrame()


#for group_name in Groups:
headers = {
      'Accept': 'application/json',
      'x-session-token':            'a3f2c8842dfbf9375060d013fbd2271f'
    }
# For each group in the groups, we iterate over all the keys we want.
for key in key_names[:1]:
#    headers = {
#      'Accept': 'application/json',
#     'x-session-token':            'a3f2c8842dfbf9375060d013fbd2271f'
#    }

    # Generate a keyname that you want for your dataframe.
    avg_key_name = key 
    print(avg_key_name)
    #std_key_name = key + '_Standard_Dev'
    smaUsed=[50,150,200]
    
    
    
    if avg_key_name not in df_info:
        df_info[avg_key_name] = 0
        #df_info[std_key_name] = []
        
    name = requests.get('https://api.stocknote.com/history/candleData', params={
      f'symbolName': {avg_key_name},  'fromDate': '2019-10-11'
    }, headers = headers)
    
    r=name.json()
    print(r)
    date1=[]
    ltp=[]
    for i in range(len(r['historicalCandleData'])):
        date1.append(r['historicalCandleData'][i]['date'])
        ltp.append(r['historicalCandleData'][i]['ltp'])
    df_info[avg_key_name]=ltp
    date1=date1
    #print(ltp)
    #df_info[std_key_name].append()
    #print(ltp)
#df_info= df_info.append(date1,axis=1)
#df_info = pd.DataFrame(df_info, index=date1)
#df_dates = df.index
df_info['date1'] = date1
#df_info['date1'] = pd.to_datetime(df['date'])
#df_info = df_info.set_index('date1')

ADANIPORTS

In [360]:
df_info

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL,date1
0,405.8,1772.25,672.1,2779.5,3959.9,8142.55,382.45,454.6,438.05,164.5,...,328.6,691.0,1238.0,4062.0,581.8,133.3,237.6,18280.0,242.65,2019-10-11
1,402.6,1780.75,684.0,2830.0,3858.0,8065.0,390.95,453.45,436.9,165.8,...,334.65,691.5,1246.55,4168.0,578.5,133.8,241.4,18565.0,241.7,2019-10-14
2,410.35,1788.75,689.9,2890.6,3874.3,8045.0,380.4,458.65,442.3,166.75,...,339.2,690.9,1268.0,4192.0,577.2,140.35,241.5,18489.0,250.3,2019-10-15
3,405.8,1752.15,692.65,2902.0,4015.0,8146.0,383.0,478.95,441.3,169.7,...,336.25,698.0,1271.0,4254.35,582.95,136.3,246.9,18590.0,259.7,2019-10-16
4,404.75,1795.65,710.35,3018.0,4086.0,8311.65,382.95,479.0,441.5,174.35,...,349.9,694.8,1272.0,4241.05,584.6,135.05,246.3,18090.0,262.4,2019-10-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,686.0,2426.0,724.75,3558.15,5357.5,9491.0,522.9,431.0,770.0,139.75,...,705.5,1020.0,1471.4,6519.0,609.0,224.1,419.45,26900.0,203.8,2021-03-17
355,680.9,2410.0,718.35,3674.55,5393.4,9445.0,530.75,428.0,758.0,137.5,...,708.15,999.6,1465.0,6524.75,602.0,222.0,410.9,26669.75,207.1,2021-03-18
356,688.0,2411.0,725.2,3645.8,5446.5,9420.9,531.9,434.1,761.0,136.4,...,731.55,983.7,1463.0,6675.0,625.0,222.1,410.9,26899.2,216.25,2021-03-19
357,721.95,2427.95,717.0,3661.5,5384.1,9402.0,527.0,438.3,772.0,135.6,...,745.0,1014.9,1462.0,6732.8,625.9,222.85,415.4,26940.15,214.0,2021-03-22
358,736.75,2410.0,730.95,3667.0,5376.0,9425.0,528.6,436.2,776.85,135.1,...,740.05,1016.0,1491.0,6900.1,633.2,223.75,415.25,28400.0,213.0,2021-03-23

In [361]:
df_info=df_info.set_index(['date1'])

In [363]:
df_info1 = (pd.to_datetime(df_info.index))

In [364]:
df_info1

DatetimeIndex(['2019-10-11', '2019-10-14', '2019-10-15', '2019-10-16',
               '2019-10-17', '2019-10-18', '2019-10-22', '2019-10-23',
               '2019-10-24', '2019-10-25',
               ...
               '2021-03-09', '2021-03-10', '2021-03-12', '2021-03-15',
               '2021-03-16', '2021-03-17', '2021-03-18', '2021-03-19',
               '2021-03-22', '2021-03-23'],
              dtype='datetime64[ns]', name='date1', length=359, freq=None)

In [365]:
df_info

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATAMOTORS,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL
date1,,,,,,,,,,,,,,,,,,,,,
2019-10-11,405.8,1772.25,672.1,2779.5,3959.9,8142.55,382.45,454.6,438.05,164.5,...,121.15,328.6,691.0,1238.0,4062.0,581.8,133.3,237.6,18280.0,242.65
2019-10-14,402.6,1780.75,684.0,2830.0,3858.0,8065.0,390.95,453.45,436.9,165.8,...,127.4,334.65,691.5,1246.55,4168.0,578.5,133.8,241.4,18565.0,241.7
2019-10-15,410.35,1788.75,689.9,2890.6,3874.3,8045.0,380.4,458.65,442.3,166.75,...,126.55,339.2,690.9,1268.0,4192.0,577.2,140.35,241.5,18489.0,250.3
2019-10-16,405.8,1752.15,692.65,2902.0,4015.0,8146.0,383.0,478.95,441.3,169.7,...,125.9,336.25,698.0,1271.0,4254.35,582.95,136.3,246.9,18590.0,259.7
2019-10-17,404.75,1795.65,710.35,3018.0,4086.0,8311.65,382.95,479.0,441.5,174.35,...,142.55,349.9,694.8,1272.0,4241.05,584.6,135.05,246.3,18090.0,262.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-17,686.0,2426.0,724.75,3558.15,5357.5,9491.0,522.9,431.0,770.0,139.75,...,305.5,705.5,1020.0,1471.4,6519.0,609.0,224.1,419.45,26900.0,203.8
2021-03-18,680.9,2410.0,718.35,3674.55,5393.4,9445.0,530.75,428.0,758.0,137.5,...,308.0,708.15,999.6,1465.0,6524.75,602.0,222.0,410.9,26669.75,207.1
2021-03-19,688.0,2411.0,725.2,3645.8,5446.5,9420.9,531.9,434.1,761.0,136.4,...,308.2,731.55,983.7,1463.0,6675.0,625.0,222.1,410.9,26899.2,216.25
2021-03-22,721.95,2427.95,717.0,3661.5,5384.1,9402.0,527.0,438.3,772.0,135.6,...,302.85,745.0,1014.9,1462.0,6732.8,625.9,222.85,415.4,26940.15,214.0
2021-03-23,736.75,2410.0,730.95,3667.0,5376.0,9425.0,528.6,436.2,776.85,135.1,...,306.9,740.05,1016.0,1491.0,6900.1,633.2,223.75,415.25,28400.0,213.0

In [295]:
df_info1.index = pd.to_datetime(df_info.index)

In [366]:
type(df_info1)

pandas.core.indexes.datetimes.DatetimeIndex

In [367]:
df_info2=df_info

In [368]:
df_info2.index=df_info1.index

AttributeError: 'DatetimeIndex' object has no attribute 'index'

In [378]:
df_info2

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATAMOTORS,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL
date1,,,,,,,,,,,,,,,,,,,,,
2019-10-11,405.8,1772.25,672.1,2779.5,3959.9,8142.55,382.45,454.6,438.05,164.5,...,121.15,328.6,691.0,1238.0,4062.0,581.8,133.3,237.6,18280.0,242.65
2019-10-14,402.6,1780.75,684.0,2830.0,3858.0,8065.0,390.95,453.45,436.9,165.8,...,127.4,334.65,691.5,1246.55,4168.0,578.5,133.8,241.4,18565.0,241.7
2019-10-15,410.35,1788.75,689.9,2890.6,3874.3,8045.0,380.4,458.65,442.3,166.75,...,126.55,339.2,690.9,1268.0,4192.0,577.2,140.35,241.5,18489.0,250.3
2019-10-16,405.8,1752.15,692.65,2902.0,4015.0,8146.0,383.0,478.95,441.3,169.7,...,125.9,336.25,698.0,1271.0,4254.35,582.95,136.3,246.9,18590.0,259.7
2019-10-17,404.75,1795.65,710.35,3018.0,4086.0,8311.65,382.95,479.0,441.5,174.35,...,142.55,349.9,694.8,1272.0,4241.05,584.6,135.05,246.3,18090.0,262.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-17,686.0,2426.0,724.75,3558.15,5357.5,9491.0,522.9,431.0,770.0,139.75,...,305.5,705.5,1020.0,1471.4,6519.0,609.0,224.1,419.45,26900.0,203.8
2021-03-18,680.9,2410.0,718.35,3674.55,5393.4,9445.0,530.75,428.0,758.0,137.5,...,308.0,708.15,999.6,1465.0,6524.75,602.0,222.0,410.9,26669.75,207.1
2021-03-19,688.0,2411.0,725.2,3645.8,5446.5,9420.9,531.9,434.1,761.0,136.4,...,308.2,731.55,983.7,1463.0,6675.0,625.0,222.1,410.9,26899.2,216.25
2021-03-22,721.95,2427.95,717.0,3661.5,5384.1,9402.0,527.0,438.3,772.0,135.6,...,302.85,745.0,1014.9,1462.0,6732.8,625.9,222.85,415.4,26940.15,214.0
2021-03-23,736.75,2410.0,730.95,3667.0,5376.0,9425.0,528.6,436.2,776.85,135.1,...,306.9,740.05,1016.0,1491.0,6900.1,633.2,223.75,415.25,28400.0,213.0

In [379]:
for column in df_info2:
    #print(df_info2[column])
    #if df_info2[column]!= date1:
    df_info2[column] = df_info2[column].str.replace('[\$\,]', '').astype(float)

In [380]:
df_info2

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATAMOTORS,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL
date1,,,,,,,,,,,,,,,,,,,,,
2019-10-11,405.80,1772.25,672.10,2779.50,3959.9,8142.55,382.45,454.60,438.05,164.50,...,121.15,328.60,691.0,1238.00,4062.00,581.80,133.30,237.60,18280.00,242.65
2019-10-14,402.60,1780.75,684.00,2830.00,3858.0,8065.00,390.95,453.45,436.90,165.80,...,127.40,334.65,691.5,1246.55,4168.00,578.50,133.80,241.40,18565.00,241.70
2019-10-15,410.35,1788.75,689.90,2890.60,3874.3,8045.00,380.40,458.65,442.30,166.75,...,126.55,339.20,690.9,1268.00,4192.00,577.20,140.35,241.50,18489.00,250.30
2019-10-16,405.80,1752.15,692.65,2902.00,4015.0,8146.00,383.00,478.95,441.30,169.70,...,125.90,336.25,698.0,1271.00,4254.35,582.95,136.30,246.90,18590.00,259.70
2019-10-17,404.75,1795.65,710.35,3018.00,4086.0,8311.65,382.95,479.00,441.50,174.35,...,142.55,349.90,694.8,1272.00,4241.05,584.60,135.05,246.30,18090.00,262.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-17,686.00,2426.00,724.75,3558.15,5357.5,9491.00,522.90,431.00,770.00,139.75,...,305.50,705.50,1020.0,1471.40,6519.00,609.00,224.10,419.45,26900.00,203.80
2021-03-18,680.90,2410.00,718.35,3674.55,5393.4,9445.00,530.75,428.00,758.00,137.50,...,308.00,708.15,999.6,1465.00,6524.75,602.00,222.00,410.90,26669.75,207.10
2021-03-19,688.00,2411.00,725.20,3645.80,5446.5,9420.90,531.90,434.10,761.00,136.40,...,308.20,731.55,983.7,1463.00,6675.00,625.00,222.10,410.90,26899.20,216.25
2021-03-22,721.95,2427.95,717.00,3661.50,5384.1,9402.00,527.00,438.30,772.00,135.60,...,302.85,745.00,1014.9,1462.00,6732.80,625.90,222.85,415.40,26940.15,214.00
2021-03-23,736.75,2410.00,730.95,3667.00,5376.0,9425.00,528.60,436.20,776.85,135.10,...,306.90,740.05,1016.0,1491.00,6900.10,633.20,223.75,415.25,28400.00,213.00

In [381]:
df_daily_returns = df_info2.pct_change()

In [382]:
df_daily_returns

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATAMOTORS,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL
date1,,,,,,,,,,,,,,,,,,,,,
2019-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-14,-0.007886,0.004796,0.017706,0.018169,-0.025733,-0.009524,0.022225,-0.002530,-0.002625,0.007903,...,0.051589,0.018411,0.000724,0.006906,0.026096,-0.005672,0.003751,0.015993,0.015591,-0.003915
2019-10-15,0.019250,0.004492,0.008626,0.021413,0.004225,-0.002480,-0.026986,0.011468,0.012360,0.005730,...,-0.006672,0.013596,-0.000868,0.017207,0.005758,-0.002247,0.048954,0.000414,-0.004094,0.035581
2019-10-16,-0.011088,-0.020461,0.003986,0.003944,0.036316,0.012554,0.006835,0.044260,-0.002261,0.017691,...,-0.005136,-0.008697,0.010276,0.002366,0.014874,0.009962,-0.028856,0.022360,0.005463,0.037555
2019-10-17,-0.002587,0.024827,0.025554,0.039972,0.017684,0.020335,-0.000131,0.000104,0.000453,0.027401,...,0.132248,0.040595,-0.004585,0.000787,-0.003126,0.002830,-0.009171,-0.002430,-0.026896,0.010397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-17,-0.041230,-0.016121,-0.017355,-0.025632,-0.017513,-0.015150,-0.013489,-0.052747,-0.028820,-0.041824,...,-0.042320,-0.026897,-0.006526,-0.021676,-0.019699,-0.017900,-0.010159,-0.023399,-0.016813,-0.031369
2021-03-18,-0.007434,-0.006595,-0.008831,0.032714,0.006701,-0.004847,0.015012,-0.006961,-0.015584,-0.016100,...,0.008183,0.003756,-0.020000,-0.004350,0.000882,-0.011494,-0.009371,-0.020384,-0.008559,0.016192
2021-03-19,0.010427,0.000415,0.009536,-0.007824,0.009845,-0.002552,0.002167,0.014252,0.003958,-0.008000,...,0.000649,0.033044,-0.015906,-0.001365,0.023028,0.038206,0.000450,0.000000,0.008603,0.044182
2021-03-22,0.049346,0.007030,-0.011307,0.004306,-0.011457,-0.002006,-0.009212,0.009675,0.014455,-0.005865,...,-0.017359,0.018386,0.031717,-0.000684,0.008659,0.001440,0.003377,0.010952,0.001522,-0.010405
2021-03-23,0.020500,-0.007393,0.019456,0.001502,-0.001504,0.002446,0.003036,-0.004791,0.006282,-0.003687,...,0.013373,-0.006644,0.001084,0.019836,0.024849,0.011663,0.004039,-0.000361,0.054189,-0.004673

In [370]:
for col in df_info2.columns:
    print(df_info2[col]+ 10)
    #df_daily_returns[col] = df_info2[col].str.replace('[\$\,]', '').astype(float).pct_change()

TypeError: can only concatenate str (not "int") to str

In [339]:
df_daily_returns = df_daily_returns['ASIANPAINT'].pct_change()

In [343]:
df_daily_returns['AXISBANK']

date1
2019-10-11         NaN
2019-10-14    0.017706
2019-10-15    0.008626
2019-10-16    0.003986
2019-10-17    0.025554
                ...
2021-03-17   -0.017355
2021-03-18   -0.008831
2021-03-19    0.009536
2021-03-22   -0.011307
2021-03-23    0.019456
Name: AXISBANK, Length: 359, dtype: float64

In [313]:
monthly_returns = df_info2.resample('M').ffill().pct_change()

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [302]:
df_monthly

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATAMOTORS,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL
date1,,,,,,,,,,,,,,,,,,,,,
2019-10-31,392.7,1797.0,732.1,3123.0,4019.0,8125.0,371.4,493.15,468.0,183.75,...,177.8,370.0,709.0,1327.8,4130.5,592.45,135.1,257.9,19889.95,260.2
2019-11-30,377.8,1694.0,738.6,3058.85,4058.0,9113.9,439.55,477.6,463.0,179.9,...,160.95,416.7,730.0,1153.6,4242.0,566.55,130.9,236.25,20939.0,286.2
2019-12-31,363.0,1778.2,752.5,3060.0,4215.0,9415.0,454.0,458.95,473.9,186.95,...,184.65,460.75,731.2,1185.9,4042.0,578.0,138.85,244.1,20277.95,291.7
2020-01-31,366.35,1785.0,731.0,3062.0,4370.1,9460.0,494.65,424.0,443.9,159.05,...,176.9,428.5,770.0,1185.55,4409.0,520.8,124.3,235.5,22890.0,267.7
2020-02-29,341.65,1798.0,701.0,2768.0,4490.0,9095.0,520.45,390.2,401.05,143.25,...,129.65,371.0,716.25,1250.9,4203.0,518.9,99.45,221.4,22633.0,238.0
2020-03-31,250.45,1651.15,378.5,2010.0,2214.3,4600.0,438.5,296.0,422.35,127.3,...,70.75,260.0,542.0,931.0,3203.0,324.0,55.4,195.1,17690.0,123.45
2020-04-30,290.65,1757.15,444.05,2623.8,2318.0,5090.0,512.55,355.85,590.0,136.3,...,93.75,287.55,525.95,963.8,3519.0,407.0,79.3,190.15,19610.0,159.3
2020-05-31,327.0,1670.15,381.9,2708.0,1940.95,4392.55,547.9,324.35,648.05,128.15,...,86.7,284.05,510.55,886.05,3862.0,398.5,82.35,210.9,20800.0,181.7
2020-06-30,346.1,1682.15,407.3,2834.0,2828.0,5833.3,558.25,357.75,640.7,120.65,...,98.75,317.25,523.6,948.25,3877.4,420.8,96.8,218.7,23040.0,171.0
2020-07-31,315.15,1716.65,432.9,3000.0,3258.0,6213.0,553.1,398.0,721.0,117.05,...,105.05,358.1,666.95,1048.5,4129.6,471.8,104.05,279.15,21670.0,138.4
2020-08-31,353.55,1891.6,492.85,2959.2,3478.5,6210.0,512.45,389.75,708.25,121.75,...,142.1,411.0,725.0,1097.0,3910.0,502.95,118.45,267.85,20180.0,201.2
2020-09-30,344.4,1978.25,423.85,2878.0,3265.0,5851.0,419.65,335.75,775.5,103.45,...,133.4,358.7,774.55,1197.1,4030.2,501.25,128.0,312.25,20184.95,210.0
2020-10-31,358.0,2210.0,491.0,2882.3,3300.0,5550.0,432.75,337.8,756.0,102.15,...,133.2,408.7,811.2,1167.55,4551.15,453.0,95.95,340.0,21604.55,187.4
2020-11-30,412.0,2198.55,605.1,3170.25,4874.8,8712.0,465.0,356.55,742.0,120.2,...,178.65,574.9,867.0,1334.0,4807.7,418.7,120.45,349.95,23811.95,191.3
2020-12-31,480.75,2760.55,619.0,3435.0,5287.5,8885.4,509.5,365.6,818.9,130.35,...,183.5,642.55,974.0,1560.25,5279.0,466.7,160.85,385.0,24000.0,223.75
2021-01-31,510.0,2412.5,666.45,4023.0,4732.15,8718.6,552.25,369.75,828.0,121.0,...,262.35,602.9,961.05,1422.0,5323.4,562.3,161.6,420.0,22550.0,219.45
2021-02-28,668.25,2278.0,725.35,3783.9,5243.55,9640.25,553.7,449.9,784.95,146.8,...,321.9,714.4,919.3,1409.95,6088.0,560.95,205.25,409.1,26236.1,200.85
2021-03-31,736.75,2410.0,730.95,3667.0,5376.0,9425.0,528.6,436.2,776.85,135.1,...,306.9,740.05,1016.0,1491.0,6900.1,633.2,223.75,415.25,28400.0,213.0

In [309]:
df_info

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,BPCL,CIPLA,COALINDIA,...,TATAMOTORS,TATASTEEL,TECHM,TITAN,ULTRACEMCO,UPL,VEDL,WIPRO,SHREECEM,ZEEL
date1,,,,,,,,,,,,,,,,,,,,,
2019-10-11,405.8,1772.25,672.1,2779.5,3959.9,8142.55,382.45,454.6,438.05,164.5,...,121.15,328.6,691.0,1238.0,4062.0,581.8,133.3,237.6,18280.0,242.65
2019-10-14,402.6,1780.75,684.0,2830.0,3858.0,8065.0,390.95,453.45,436.9,165.8,...,127.4,334.65,691.5,1246.55,4168.0,578.5,133.8,241.4,18565.0,241.7
2019-10-15,410.35,1788.75,689.9,2890.6,3874.3,8045.0,380.4,458.65,442.3,166.75,...,126.55,339.2,690.9,1268.0,4192.0,577.2,140.35,241.5,18489.0,250.3
2019-10-16,405.8,1752.15,692.65,2902.0,4015.0,8146.0,383.0,478.95,441.3,169.7,...,125.9,336.25,698.0,1271.0,4254.35,582.95,136.3,246.9,18590.0,259.7
2019-10-17,404.75,1795.65,710.35,3018.0,4086.0,8311.65,382.95,479.0,441.5,174.35,...,142.55,349.9,694.8,1272.0,4241.05,584.6,135.05,246.3,18090.0,262.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-17,686.0,2426.0,724.75,3558.15,5357.5,9491.0,522.9,431.0,770.0,139.75,...,305.5,705.5,1020.0,1471.4,6519.0,609.0,224.1,419.45,26900.0,203.8
2021-03-18,680.9,2410.0,718.35,3674.55,5393.4,9445.0,530.75,428.0,758.0,137.5,...,308.0,708.15,999.6,1465.0,6524.75,602.0,222.0,410.9,26669.75,207.1
2021-03-19,688.0,2411.0,725.2,3645.8,5446.5,9420.9,531.9,434.1,761.0,136.4,...,308.2,731.55,983.7,1463.0,6675.0,625.0,222.1,410.9,26899.2,216.25
2021-03-22,721.95,2427.95,717.0,3661.5,5384.1,9402.0,527.0,438.3,772.0,135.6,...,302.85,745.0,1014.9,1462.0,6732.8,625.9,222.85,415.4,26940.15,214.0
2021-03-23,736.75,2410.0,730.95,3667.0,5376.0,9425.0,528.6,436.2,776.85,135.1,...,306.9,740.05,1016.0,1491.0,6900.1,633.2,223.75,415.25,28400.0,213.0

In [305]:
df_info2 = pd.DataFrame( dtype=float)

In [ ]:
s

In [308]:
df_info2

Empty DataFrame
Columns: []
Index: []

In [306]:
r = df_info2.pct_change()

In [307]:
r

Empty DataFrame
Columns: []
Index: []

In [303]:
#clculate monthly return by cumulating daily return
mthly_return=df_info2.pct_change().resample('M').agg(lambda x:(x+1).prod()-1)
mthly_return

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [66]:
# These are all the keys you want
key_names= nifty_50 

# Holds the data you want to pass to the dataframe.
df_info = pd.DataFrame()
df_temp= pd.DataFrame()

#for group_name in Groups:
headers = {
      'Accept': 'application/json',
      'x-session-token':            'a3f2c8842dfbf9375060d013fbd2271f'
    }
# For each group in the groups, we iterate over all the keys we want.

RS_Rating=80
exportList= pd.DataFrame(columns=['Stock', "RS_Rating", "50 Day MA", "150 Day Ma", "200 Day MA", "52 Week Low", "52 week High"])
for key in key_names:
#    headers = {
#      'Accept': 'application/json',
#     'x-session-token':            'a3f2c8842dfbf9375060d013fbd2271f'
#    }

    # Generate a keyname that you want for your dataframe.
    avg_key_name = key 
    print(avg_key_name)
    #std_key_name = key + '_Standard_Dev'
    smaUsed=[50,150,200]
    
    
    
    if avg_key_name not in df_info:
        df_info[avg_key_name] = 0
        #df_info[std_key_name] = []
        
    name = requests.get('https://api.stocknote.com/history/candleData', params={
      f'symbolName': {avg_key_name},  'fromDate': '2019-10-11'
    }, headers = headers)
    
    r=name.json()
    #print(r)
    
    date1=[]
    ltp=[]
    open1=[]
    low1=[]
    high=[]
    volume=[]
    
    for i in range(len(r['historicalCandleData'])):
        date1.append(r['historicalCandleData'][i]['date'])
        ltp.append(r['historicalCandleData'][i]['ltp'])
        open1.append(r['historicalCandleData'][i]['open'])
        low1.append(r['historicalCandleData'][i]['low'])
        high.append(r['historicalCandleData'][i]['high'])
        volume.append(r['historicalCandleData'][i]['volume'])
    df_info[avg_key_name]=ltp
    date1=date1
    df_temp['date']=date1
    df_temp['ltp']= ltp
    df_temp['open']=open1
    df_temp['low']=low1
    df_temp['high']=high
    df_temp['volume']=volume
    #smaUsed=[50,150,200]
    for x in smaUsed:
        sma=x
        df_temp["SMA_"+str(sma)]=round(df_temp.iloc[:,4].rolling(window=sma).mean(),2)
    
    #print((df_temp))
    currentClose=df_temp["ltp"][len(df_temp)-1]
    moving_average_50=df_temp["SMA_50"][len(df_temp)-1]
    moving_average_150=df_temp["SMA_150"][len(df_temp)-1]
    moving_average_200=df_temp["SMA_200"][len(df_temp)-1]
    low_of_52week=min(df_temp["ltp"][-260:])
    high_of_52week=max(df_temp["ltp"][-260:])
    currentClose =       float(currentClose)
    moving_average_50 =  float(moving_average_50)
    moving_average_150 = float(moving_average_150)
    moving_average_200 = float(moving_average_200)
    low_of_52week =  float(low_of_52week)
    high_of_52week =  float(high_of_52week)
        
    
    
    
    try:
        moving_average_200_20 = df_temp["SMA_200"][-20]

    except Exception:
        moving_average_200_20=0
        
        #Condition 1: Current Price > 150 SMA and > 200 SMA
    if(currentClose>moving_average_150>moving_average_200):
        cond_1=True
    else:
        cond_1=False
        #Condition 2: 150 SMA and > 200 SMA
    if(moving_average_150>moving_average_200):
        cond_2=True
    else:
        cond_2=False
        #Condition 3: 200 SMA trending up for at least 1 month (ideally 4-5 months)
    if(moving_average_200>moving_average_200_20):
        cond_3=True
    else:
        cond_3=False
        #Condition 4: 50 SMA> 150 SMA and 50 SMA> 200 SMA
    if(moving_average_50>moving_average_150>moving_average_200):
        #print("Condition 4 met")
        cond_4=True
    else:
        #print("Condition 4 not met")
        cond_4=False
        #Condition 5: Current Price > 50 SMA
    if(currentClose>moving_average_50):
        cond_5=True
    else:
        cond_5=False
    #Condition 6: Current Price is at least 30% above 52 week low (Many of the best are up 100-300% before coming out of consolidation)
    if(currentClose>=(1.3*low_of_52week)):
        cond_6=True
    else:
        cond_6=False
        #Condition 7: Current Price is within 25% of 52 week high
    if(currentClose>=(.75*high_of_52week)):
        cond_7=True
    else:
        cond_7=False
    #Condition 8: IBD RS rating >70 and the higher the better
    if(RS_Rating>70):
        cond_8=True
    else:
        cond_8=False
        
    if(cond_1 and cond_2 and cond_3 and cond_4 and cond_5 and cond_6 and cond_7 and cond_8):
        exportList = exportList.append({'Stock': avg_key_name, "RS_Rating": RS_Rating, "50 Day MA": moving_average_50, "150 Day Ma": moving_average_150, "200 Day MA": moving_average_200, "52 Week Low": low_of_52week, "52 week High": high_of_52week}, ignore_index=True)
    #except Exception:
        #print("No data on "+stock)



    
    
    #print(ltp)
    #df_info[std_key_name].append()
    #print(ltp)
#df_info= df_info.append(date1,axis=1)
#df_info = pd.DataFrame(df_info, index=date1)
#df_dates = df.index
df_info['date1'] = date1
#df_info['date1'] = pd.to_datetime(df['date'])
#df_info = df_info.set_index('date1')

ADANIPORTS
ASIANPAINT
AXISBANK
BAJAJ-AUTO
BAJFINANCE
BAJAJFINSV
BHARTIARTL
BPCL
CIPLA
COALINDIA
DRREDDY
EICHERMOT
GAIL
GRASIM
HCLTECH
HDFC
HDFCBANK
HEROMOTOCO
HINDALCO
HINDUNILVR
BRITANNIA
ICICIBANK
INDUSINDBK
INFY
IOC
ITC
JSWSTEEL
KOTAKBANK
LT
M&M
MARUTI
NESTLEIND
NTPC
ONGC
POWERGRID
RELIANCE
SBIN
SUNPHARMA
TCS
TATAMOTORS
TATASTEEL
TECHM
TITAN
ULTRACEMCO
UPL
VEDL
WIPRO
SHREECEM
ZEEL

In [67]:
exportList

,Stock,RS_Rating,50 Day MA,150 Day Ma,200 Day MA,52 Week Low,52 week High
0,ADANIPORTS,80,650.04,484.54,448.42,215.00,751.55
1,ASIANPAINT,80,2497.07,2344.58,2195.48,1495.10,2846.00
2,GRASIM,80,1253.64,967.87,881.76,1000.65,994.85
3,HINDALCO,80,304.37,240.64,221.97,100.15,99.50
4,INFY,80,1333.05,1184.65,1101.52,1001.85,999.00
5,JSWSTEEL,80,414.95,359.08,323.97,140.35,445.40
6,TATASTEEL,80,713.41,570.44,517.26,244.35,774.80
7,TITAN,80,1502.75,1377.47,1293.05,1002.75,999.00
8,ULTRACEMCO,80,6349.36,5220.33,4908.28,3017.00,6900.10
9,VEDL,80,200.29,150.99,139.84,100.00,99.85
10,SHREECEM,80,27087.83,24074.47,23643.81,15500.00,28720.00